// ============================================================
// Daftar kota/kabupaten utama Indonesia untuk pemilih lokasi (form titip jual).
// Dikelompokkan per provinsi. (Data prompt dirapikan: Yogyakarta → DI Yogyakarta,
// entri keliru dihapus.) Cukup untuk dropdown provinsi → kota.
// ============================================================
export const INDONESIA_CITIES = [
  { name: 'Banda Aceh', province: 'Aceh' },
  { name: 'Lhokseumawe', province: 'Aceh' },
  { name: 'Langsa', province: 'Aceh' },
  { name: 'Medan', province: 'Sumatera Utara' },
  { name: 'Binjai', province: 'Sumatera Utara' },
  { name: 'Pematangsiantar', province: 'Sumatera Utara' },
  { name: 'Tebing Tinggi', province: 'Sumatera Utara' },
  { name: 'Padang', province: 'Sumatera Barat' },
  { name: 'Bukittinggi', province: 'Sumatera Barat' },
  { name: 'Padang Panjang', province: 'Sumatera Barat' },
  { name: 'Payakumbuh', province: 'Sumatera Barat' },
  { name: 'Pekanbaru', province: 'Riau' },
  { name: 'Dumai', province: 'Riau' },
  { name: 'Tanjung Pinang', province: 'Kepulauan Riau' },
  { name: 'Batam', province: 'Kepulauan Riau' },
  { name: 'Jambi', province: 'Jambi' },
  { name: 'Sungai Penuh', province: 'Jambi' },
  { name: 'Palembang', province: 'Sumatera Selatan' },
  { name: 'Lubuk Linggau', province: 'Sumatera Selatan' },
  { name: 'Prabumulih', province: 'Sumatera Selatan' },
  { name: 'Pangkal Pinang', province: 'Kepulauan Bangka Belitung' },
  { name: 'Bengkulu', province: 'Bengkulu' },
  { name: 'Bandar Lampung', province: 'Lampung' },
  { name: 'Metro', province: 'Lampung' },
  { name: 'Jakarta Pusat', province: 'DKI Jakarta' },
  { name: 'Jakarta Utara', province: 'DKI Jakarta' },
  { name: 'Jakarta Timur', province: 'DKI Jakarta' },
  { name: 'Jakarta Selatan', province: 'DKI Jakarta' },
  { name: 'Jakarta Barat', province: 'DKI Jakarta' },
  { name: 'Bandung', province: 'Jawa Barat' },
  { name: 'Bogor', province: 'Jawa Barat' },
  { name: 'Depok', province: 'Jawa Barat' },
  { name: 'Bekasi', province: 'Jawa Barat' },
  { name: 'Cirebon', province: 'Jawa Barat' },
  { name: 'Tasikmalaya', province: 'Jawa Barat' },
  { name: 'Sukabumi', province: 'Jawa Barat' },
  { name: 'Cimahi', province: 'Jawa Barat' },
  { name: 'Serang', province: 'Banten' },
  { name: 'Tangerang', province: 'Banten' },
  { name: 'Tangerang Selatan', province: 'Banten' },
  { name: 'Cilegon', province: 'Banten' },
  { name: 'Semarang', province: 'Jawa Tengah' },
  { name: 'Surakarta (Solo)', province: 'Jawa Tengah' },
  { name: 'Pekalongan', province: 'Jawa Tengah' },
  { name: 'Tegal', province: 'Jawa Tengah' },
  { name: 'Magelang', province: 'Jawa Tengah' },
  { name: 'Salatiga', province: 'Jawa Tengah' },
  { name: 'Yogyakarta', province: 'DI Yogyakarta' },
  { name: 'Sleman', province: 'DI Yogyakarta' },
  { name: 'Bantul', province: 'DI Yogyakarta' },
  { name: 'Surabaya', province: 'Jawa Timur' },
  { name: 'Malang', province: 'Jawa Timur' },
  { name: 'Sidoarjo', province: 'Jawa Timur' },
  { name: 'Gresik', province: 'Jawa Timur' },
  { name: 'Pasuruan', province: 'Jawa Timur' },
  { name: 'Mojokerto', province: 'Jawa Timur' },
  { name: 'Kediri', province: 'Jawa Timur' },
  { name: 'Blitar', province: 'Jawa Timur' },
  { name: 'Batu', province: 'Jawa Timur' },
  { name: 'Jember', province: 'Jawa Timur' },
  { name: 'Banyuwangi', province: 'Jawa Timur' },
  { name: 'Denpasar', province: 'Bali' },
  { name: 'Badung', province: 'Bali' },
  { name: 'Gianyar', province: 'Bali' },
  { name: 'Mataram', province: 'Nusa Tenggara Barat' },
  { name: 'Kupang', province: 'Nusa Tenggara Timur' },
  { name: 'Pontianak', province: 'Kalimantan Barat' },
  { name: 'Singkawang', province: 'Kalimantan Barat' },
  { name: 'Palangka Raya', province: 'Kalimantan Tengah' },
  { name: 'Banjarmasin', province: 'Kalimantan Selatan' },
  { name: 'Banjarbaru', province: 'Kalimantan Selatan' },
  { name: 'Samarinda', province: 'Kalimantan Timur' },
  { name: 'Balikpapan', province: 'Kalimantan Timur' },
  { name: 'Bontang', province: 'Kalimantan Timur' },
  { name: 'Tarakan', province: 'Kalimantan Utara' },
  { name: 'Manado', province: 'Sulawesi Utara' },
  { name: 'Bitung', province: 'Sulawesi Utara' },
  { name: 'Tomohon', province: 'Sulawesi Utara' },
  { name: 'Palu', province: 'Sulawesi Tengah' },
  { name: 'Makassar', province: 'Sulawesi Selatan' },
  { name: 'Palopo', province: 'Sulawesi Selatan' },
  { name: 'Parepare', province: 'Sulawesi Selatan' },
  { name: 'Kendari', province: 'Sulawesi Tenggara' },
  { name: 'Bau-Bau', province: 'Sulawesi Tenggara' },
  { name: 'Gorontalo', province: 'Gorontalo' },
  { name: 'Mamuju', province: 'Sulawesi Barat' },
  { name: 'Ambon', province: 'Maluku' },
  { name: 'Ternate', province: 'Maluku Utara' },
  { name: 'Tidore', province: 'Maluku Utara' },
  { name: 'Jayapura', province: 'Papua' },
  { name: 'Manokwari', province: 'Papua Barat' },
  { name: 'Sorong', province: 'Papua Barat Daya' },
]

// Provinsi unik (untuk dropdown pertama), terurut.
export const PROVINCES = [...new Set(INDONESIA_CITIES.map((c) => c.province))].sort((a, b) => a.localeCompare(b, 'id'))

// Kota dalam satu provinsi (untuk dropdown kedua).
export const citiesOf = (province) => INDONESIA_CITIES.filter((c) => c.province === province).map((c) => c.name)
